# 周期
hz: 10

# デバッグ用
test_show: false
sleep_time: 0.005

# 経由点
way_points_x: [0.0, 13.58,  13.58, -2.60, -19.80, -19.80, 0.0]
way_points_y: [0.0,   0.0,  14.13, 14.13,  14.13,    0.0, 0.0]

# 車両マージン
margin: 0.25
