# 周期
hz: 10

# デバッグ用
test_show: true
sleep_time: 0.005

# 経由点
way_points_x: [0.0, 9.17,  9.17, -7.43, -24.47, -24.47, 0.0]
way_points_y: [2.0,  2.0, 16.24, 16.24,  16.24,    2.0, 2.0]

# 車両マージン
margin: 0.25
