hz: 10
goal_tolerance: 0.1
max_vel: 0.4
min_vel: 0.0
max_yawrate: 1.0
max_accel: 1000.0
max_dyawrate: 1000.0
dt: 0.1
predict_time: 3.0
weight_heading: 0.9
weight_distance: 1.5
weight_velocity: 0.5
search_range: 1.0
roomba_radius: 0.2
radius_margin: 0.2
vel_reso: 0.01
yawrate_reso: 0.01
